### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Martin36** [Martin36/DH2321-Individual-Projects#1]
- [ ] Add functionality for removing persons from the group

- [x] Make a list that shows persons in the group

- [x] Add more description for how to use it

- [ ] Fix the layout
